// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenShock.RepositoryServer.Enums;
using OpenShock.RepositoryServer.RepoServerDb;

#nullable disable

namespace OpenShock.RepositoryServer.Migrations
{
    [DbContext(typeof(MigrationOpenShockContext))]
    [Migration("20260814202828_DataProtectionKeys")]
    partial class DataProtectionKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "advisory_severity", new[] { "critical", "info", "warning" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "discord_notification_event", new[] { "desktop_module_version_published", "firmware_release_published", "release_notes_need_editing", "staged_release_expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_artifact_type", new[] { "app", "bootloader", "merged", "partitions", "static_fs" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_chip_architecture", new[] { "risc_v", "xtensa" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_release_note_type", new[] { "breaking", "info", "section", "warning" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "release_channel", new[] { "beta", "develop", "stable" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "release_status", new[] { "aborted", "archived", "editing", "published", "staging" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "repository_provider", new[] { "github" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "repository_scope", new[] { "publish_firmware", "publish_modules" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.DiscordWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.PrimitiveCollection<DiscordNotificationEvent[]>("Events")
                        .IsRequired()
                        .HasColumnType("discord_notification_event[]")
                        .HasColumnName("events");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("discord_webhooks_pkey");

                    b.ToTable("discord_webhooks", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareAdvisory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AffectedVersions")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("affected_versions");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<AdvisorySeverity>("Severity")
                        .HasColumnType("advisory_severity")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("firmware_advisories_pkey");

                    b.ToTable("firmware_advisories", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareArtifact", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<FirmwareArtifactType>("ArtifactType")
                        .HasColumnType("firmware_artifact_type")
                        .HasColumnName("artifact_type");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<byte[]>("HashSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash_sha256");

                    b.HasKey("Version", "BoardId", "ArtifactType")
                        .HasName("firmware_artifacts_pkey");

                    b.HasIndex("BoardId");

                    b.ToTable("firmware_artifacts", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChipId")
                        .HasColumnType("uuid")
                        .HasColumnName("chip_id");

                    b.Property<bool>("Discontinued")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("discontinued");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<FirmwareArtifactType[]>("RequiredArtifactTypes")
                        .IsRequired()
                        .HasColumnType("firmware_artifact_type[]")
                        .HasColumnName("required_artifact_types");

                    b.HasKey("Id")
                        .HasName("firmware_boards_pkey");

                    b.HasIndex("ChipId");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_firmware_boards_name");

                    b.ToTable("firmware_boards", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareBoardUsbDevice", b =>
                {
                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<Guid>("UsbDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("usb_device_id");

                    b.HasKey("BoardId", "UsbDeviceId")
                        .HasName("firmware_board_usb_devices_pkey");

                    b.HasIndex("UsbDeviceId");

                    b.ToTable("firmware_board_usb_devices", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareChip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<FirmwareChipArchitecture?>("Architecture")
                        .HasColumnType("firmware_chip_architecture")
                        .HasColumnName("architecture");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("firmware_chips_pkey");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_firmware_chips_name");

                    b.ToTable("firmware_chips", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareChipUsbDevice", b =>
                {
                    b.Property<Guid>("ChipId")
                        .HasColumnType("uuid")
                        .HasColumnName("chip_id");

                    b.Property<Guid>("UsbDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("usb_device_id");

                    b.HasKey("ChipId", "UsbDeviceId")
                        .HasName("firmware_chip_usb_devices_pkey");

                    b.HasIndex("UsbDeviceId");

                    b.ToTable("firmware_chip_usb_devices", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<ReleaseChannel>("Channel")
                        .HasColumnType("release_channel")
                        .HasColumnName("channel");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<Guid[]>("DeclaredBoards")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("declared_boards");

                    b.Property<string>("Ref")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ref");

                    b.Property<DateTimeOffset>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("run_id");

                    b.Property<ReleaseStatus>("Status")
                        .HasColumnType("release_status")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("firmware_releases_pkey");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("Version", "Status")
                        .HasDatabaseName("ix_firmware_releases_version_status");

                    b.ToTable("firmware_releases", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareReleaseNote", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<ReleaseNoteSectionType>("SectionType")
                        .HasColumnType("firmware_release_note_type")
                        .HasColumnName("type");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Version", "Index")
                        .HasName("firmware_release_notes_pkey");

                    b.ToTable("firmware_release_notes", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareStagedArtifact", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<FirmwareArtifactType>("ArtifactType")
                        .HasColumnType("firmware_artifact_type")
                        .HasColumnName("artifact_type");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<byte[]>("HashSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash_sha256");

                    b.HasKey("ReleaseId", "BoardId", "ArtifactType")
                        .HasName("firmware_staged_artifacts_pkey");

                    b.ToTable("firmware_staged_artifacts", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareStagedReleaseNote", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<ReleaseNoteSectionType>("SectionType")
                        .HasColumnType("firmware_release_note_type")
                        .HasColumnName("type");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("ReleaseId", "Index")
                        .HasName("firmware_staged_release_notes_pkey");

                    b.ToTable("firmware_staged_release_notes", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareVersion", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<ReleaseChannel>("Channel")
                        .HasColumnType("release_channel")
                        .HasColumnName("channel");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit_hash");

                    b.Property<string>("Ref")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ref");

                    b.Property<DateTimeOffset>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("run_id");

                    b.HasKey("Version")
                        .HasName("firmware_versions_pkey");

                    b.HasIndex("Channel")
                        .HasDatabaseName("ix_firmware_versions_channel");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("ix_firmware_versions_release_date");

                    b.HasIndex("RepositoryId");

                    b.ToTable("firmware_versions", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.Module", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("modules_pkey");

                    b.HasIndex("RepositoryId");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.SourceRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner");

                    b.Property<RepositoryProvider>("Provider")
                        .HasColumnType("repository_provider")
                        .HasColumnName("provider");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("repo");

                    b.PrimitiveCollection<RepositoryScope[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("repository_scope[]")
                        .HasColumnName("scopes");

                    b.HasKey("Id")
                        .HasName("repositories_pkey");

                    b.HasIndex("Provider", "Owner", "Repo")
                        .HasDatabaseName("ix_repositories_provider_owner_repo");

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.UsbDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Pid")
                        .HasColumnType("integer")
                        .HasColumnName("pid");

                    b.Property<int>("Vid")
                        .HasColumnType("integer")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("usb_devices_pkey");

                    b.HasIndex("Vid", "Pid")
                        .IsUnique()
                        .HasDatabaseName("ix_usb_devices_vid_pid");

                    b.ToTable("usb_devices", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.UsbSerialFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<int?>("Pid")
                        .HasColumnType("integer")
                        .HasColumnName("pid");

                    b.Property<int>("Vid")
                        .HasColumnType("integer")
                        .HasColumnName("vid");

                    b.HasKey("Id")
                        .HasName("usb_serial_filters_pkey");

                    b.HasIndex("Vid", "Pid")
                        .IsUnique()
                        .HasDatabaseName("ix_usb_serial_filters_vid_pid");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Vid", "Pid"), false);

                    b.ToTable("usb_serial_filters", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.Version", b =>
                {
                    b.Property<string>("VersionName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<string>("Module")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("module");

                    b.Property<string>("ChangelogUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("changelog_url");

                    b.Property<byte[]>("HashSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash_sha256");

                    b.Property<string>("ReleaseUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("release_url");

                    b.Property<string>("ZipUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("zip_url");

                    b.HasKey("VersionName", "Module")
                        .HasName("versions_pkey");

                    b.HasIndex("Module");

                    b.ToTable("versions", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareArtifact", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareBoard", "BoardNavigation")
                        .WithMany("Artifacts")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_artifacts_board");

                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareVersion", "VersionNavigation")
                        .WithMany("Artifacts")
                        .HasForeignKey("Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_artifacts_version");

                    b.Navigation("BoardNavigation");

                    b.Navigation("VersionNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareBoard", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareChip", "ChipNavigation")
                        .WithMany("Boards")
                        .HasForeignKey("ChipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_boards_chip");

                    b.Navigation("ChipNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareBoardUsbDevice", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareBoard", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_board_usb_devices_board");

                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.UsbDevice", "UsbDevice")
                        .WithMany()
                        .HasForeignKey("UsbDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_board_usb_devices_usb_device");

                    b.Navigation("Board");

                    b.Navigation("UsbDevice");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareChipUsbDevice", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareChip", "Chip")
                        .WithMany()
                        .HasForeignKey("ChipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_chip_usb_devices_chip");

                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.UsbDevice", "UsbDevice")
                        .WithMany()
                        .HasForeignKey("UsbDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_chip_usb_devices_usb_device");

                    b.Navigation("Chip");

                    b.Navigation("UsbDevice");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareRelease", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.SourceRepository", "RepositoryNavigation")
                        .WithMany("FirmwareReleases")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_releases_repository");

                    b.Navigation("RepositoryNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareReleaseNote", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareVersion", "VersionNavigation")
                        .WithMany("ReleaseNotes")
                        .HasForeignKey("Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_release_notes_version");

                    b.Navigation("VersionNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareStagedArtifact", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareRelease", "ReleaseNavigation")
                        .WithMany("StagedArtifacts")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_staged_artifacts_release");

                    b.Navigation("ReleaseNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareStagedReleaseNote", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareRelease", "ReleaseNavigation")
                        .WithMany("StagedReleaseNotes")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_staged_release_notes_release");

                    b.Navigation("ReleaseNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareVersion", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.SourceRepository", "RepositoryNavigation")
                        .WithMany("FirmwareVersions")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_versions_repository");

                    b.Navigation("RepositoryNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.Module", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.SourceRepository", "RepositoryNavigation")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_modules_repository");

                    b.Navigation("RepositoryNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.Version", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Models.Module", "ModuleNavigation")
                        .WithMany("Versions")
                        .HasForeignKey("Module")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_versions_module");

                    b.Navigation("ModuleNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareBoard", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareChip", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareRelease", b =>
                {
                    b.Navigation("StagedArtifacts");

                    b.Navigation("StagedReleaseNotes");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.FirmwareVersion", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("ReleaseNotes");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.Module", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Models.SourceRepository", b =>
                {
                    b.Navigation("FirmwareReleases");

                    b.Navigation("FirmwareVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
