// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenShock.RepositoryServer.RepoServerDb;

#nullable disable

namespace OpenShock.RepositoryServer.Migrations
{
    [DbContext(typeof(MigrationOpenShockContext))]
    [Migration("20260211110324_AddFirmwareTables")]
    partial class AddFirmwareTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_artifact_type", new[] { "app", "bootloader", "merged", "partitions", "static_fs" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_artifact_type", "firmware_artifact_type", new[] { "merged", "app", "bootloader", "partitions", "static_fs" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_channel", new[] { "beta", "develop", "stable" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_channel", "firmware_channel", new[] { "stable", "beta", "develop" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_chip_architecture", new[] { "risc_v", "xtensa" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_chip_architecture", "firmware_chip_architecture", new[] { "xtensa", "risc_v" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_release_note_type", new[] { "breaking", "info", "section", "warning" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "firmware_release_note_type", "firmware_release_note_type", new[] { "warning", "info", "breaking", "section" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareArtifact", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<string>("BoardId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("board_id");

                    b.Property<FirmwareArtifactType>("ArtifactType")
                        .HasColumnType("firmware_artifact_type")
                        .HasColumnName("artifact_type");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<byte[]>("HashSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash_sha256");

                    b.HasKey("Version", "BoardId", "ArtifactType")
                        .HasName("firmware_artifacts_pkey");

                    b.HasIndex("BoardId");

                    b.ToTable("firmware_artifacts", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareBoard", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("ChipId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chip_id");

                    b.Property<bool>("Discontinued")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("discontinued");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("firmware_boards_pkey");

                    b.HasIndex("ChipId");

                    b.ToTable("firmware_boards", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareChip", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<FirmwareChipArchitecture?>("Architecture")
                        .HasColumnType("firmware_chip_architecture")
                        .HasColumnName("architecture");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("firmware_chips_pkey");

                    b.ToTable("firmware_chips", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareReleaseNote", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<FirmwareReleaseNoteType>("Type")
                        .HasColumnType("firmware_release_note_type")
                        .HasColumnName("type");

                    b.HasKey("Version", "Index")
                        .HasName("firmware_release_notes_pkey");

                    b.ToTable("firmware_release_notes", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareVersion", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<FirmwareChannel>("Channel")
                        .HasColumnType("firmware_channel")
                        .HasColumnName("channel");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit_hash");

                    b.Property<DateTimeOffset>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<string>("ReleaseUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("release_url");

                    b.HasKey("Version")
                        .HasName("firmware_versions_pkey");

                    b.HasIndex("Channel")
                        .HasDatabaseName("ix_firmware_versions_channel");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("ix_firmware_versions_release_date");

                    b.ToTable("firmware_versions", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Module", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("modules_pkey");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Version", b =>
                {
                    b.Property<string>("VersionName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.Property<string>("Module")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("module");

                    b.Property<string>("ChangelogUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("changelog_url");

                    b.Property<byte[]>("HashSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash_sha256");

                    b.Property<string>("ReleaseUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("release_url");

                    b.Property<string>("ZipUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("zip_url");

                    b.HasKey("VersionName", "Module")
                        .HasName("versions_pkey");

                    b.HasIndex("Module");

                    b.ToTable("versions", (string)null);
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareArtifact", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.FirmwareBoard", "BoardNavigation")
                        .WithMany("Artifacts")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_artifacts_board");

                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.FirmwareVersion", "VersionNavigation")
                        .WithMany("Artifacts")
                        .HasForeignKey("Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_artifacts_version");

                    b.Navigation("BoardNavigation");

                    b.Navigation("VersionNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareBoard", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.FirmwareChip", "ChipNavigation")
                        .WithMany("Boards")
                        .HasForeignKey("ChipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_boards_chip");

                    b.Navigation("ChipNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareReleaseNote", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.FirmwareVersion", "VersionNavigation")
                        .WithMany("ReleaseNotes")
                        .HasForeignKey("Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firmware_release_notes_version");

                    b.Navigation("VersionNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Version", b =>
                {
                    b.HasOne("OpenShock.RepositoryServer.RepoServerDb.Module", "ModuleNavigation")
                        .WithMany("Versions")
                        .HasForeignKey("Module")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_versions_module");

                    b.Navigation("ModuleNavigation");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareBoard", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareChip", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.FirmwareVersion", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("ReleaseNotes");
                });

            modelBuilder.Entity("OpenShock.RepositoryServer.RepoServerDb.Module", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
